### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Murat-Suicmez** [ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar#42] opened 2022-12-13 17:51 UTC
[2022-12-13.txt](https://github.com/ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar/files/10220745/2022-12-13.txt)
Flow Launcher version: 1.10.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/13/2022 18:50:17
Exception:
Google Calendar Exception: 
Websites: https://github.com/ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar
Author: Ilja van Ipenburg
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Failed to produce result for "wat gebeurt er"

 ---> System.IO.InvalidDataException: Failed to produce result for "wat gebeurt er"

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 312
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 740
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 741
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ivanipenburg** [comment] 2022-12-13 18:01
Hi! 

Thanks for creating the issue. Somehow the new Flow Launcher update broke the plugin. 

I just published a fix for this 40 minutes ago which you can find in the Releases tab (version 1.1.0). It should also be available through Flow Launcher in a few hours once the plugins are automatically updated.

Please let me know if the issue is fixed once the update is available.

Groetjes,  Ilja

**Comment by Murat-Suicmez** [comment] 2022-12-13 18:05
Im sorry where can I find it it's my first time using Github actually 😆

**Comment by ivanipenburg** [comment] 2022-12-13 18:10
You can find the release here: https://github.com/ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar/releases/tag/v1.1.0

If you want to update the plugin manually, you can download 'Flow.Launcher.Plugin.GoogleCalendar.zip' from that page, unzip it and copy it to the plugin folder. You can find that folder if you type in 'userdata' in Flow Launcher, press Enter, and navigate to 'Plugins/Google Calendar-1.0.1'. Just clear everything there except your credentials and copy the files.

If you don't want to do this, you can wait a few hours until Flow Launcher automatically updates the plugin.

**Closed** 2022-12-15 12:39 UTC
